# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S4 Upmu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S4 Upmu

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FirebaseUI/Auth'
pod 'FSCalendar'

end
